# Generated by Django 5.0.6 on 2026-07-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(db_column='userid', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='userdisplayname', max_length=150, unique=True)),
                ('password', models.TextField(db_column='userpassword', default='')),
                ('status', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('golden', 'Golden')], db_column='userstatus', default='bronze', max_length=40)),
                ('email', models.EmailField(db_column='useremail', default='', max_length=254)),
                ('is_inquisitor', models.BooleanField(db_column='userisinquisitor', default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('user', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.profile')),
                ('banned_ip', models.CharField(db_column='bannedip', max_length=40)),
            ],
            options={
                'db_table': 'bannedips',
            },
        ),
    ]
