services:
  postgres-db:
    build:
      context: .
      dockerfile: DB_Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - backend 
    volumes:
      - data_sql:/var/lib/postgresql
  backend-django:
    build:
      context: ./backend-django
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      - backend 
      - frontend
    volumes:
      - ./backend-django:/app
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0


networks:
  backend:
    driver: bridge
    name: backend_net
  frontend:
    driver: bridge
    name: frontend_net

volumes:
  data_sql: