services:

  main-db:
    image: postgres:18
    container_name: main-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${MAIN_DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - backend 
    volumes:
      - main_data_sql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env


  frontend:
    build:
      context: ./frontend
      args:
        - VITE_POSTING_SERVICE_URL=${VITE_POSTING_SERVICE_URL}
    networks:
      - frontend
      - backend
    ports:
      - "3000:3000"
    depends_on:
      posting:
        condition: service_started
    env_file:
      - .env

  main-flyway:
    image: flyway/flyway:13
    entrypoint: ["flyway", "-url=jdbc:${MAIN_DATABASE_URL}", "-user=${POSTGRES_USER}", "-password=${POSTGRES_PASSWORD}", "-baselineOnMigrate=true", "-baselineVersion=0", "-validateMigrationNaming=true", "migrate"]
    volumes:
      - ./db/migrations/main-db:/flyway/sql
    depends_on:
      main-db:
        condition: service_healthy
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${MAIN_DB_NAME}
      DATABASE_URL: ${MAIN_DATABASE_URL}
    env_file: .env
  
  map-db:
    image: postgres:18
    container_name: map-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${MAP_DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - backend 
    volumes:
      - map_data_sql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env
  
  map-flyway:
    image: flyway/flyway:13
    entrypoint: ["flyway", "-url=jdbc:${MAP_DATABASE_URL}", "-user=${POSTGRES_USER}", "-password=${POSTGRES_PASSWORD}", "-baselineOnMigrate=true", "-baselineVersion=0", "-validateMigrationNaming=true", "migrate"] 
    volumes:
      - ./db/migrations/mysterymap-db:/flyway/sql
    depends_on:
      map-db:
        condition: service_healthy
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${MAP_DB_NAME}
      DATABASE_URL: ${MAP_DATABASE_URL}
    env_file: .env

  voting-db:
    image: postgres:18
    container_name: voting-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${VOTING_DB_NAME}
    ports:
      - "5434:5432"
    networks:
      - backend 
    volumes:
      - voting_data_sql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env
  
  voting-flyway:
    image: flyway/flyway:13
    entrypoint: ["flyway", "-url=jdbc:${VOTING_DATABASE_URL}", "-user=${POSTGRES_USER}", "-password=${POSTGRES_PASSWORD}", "-baselineOnMigrate=true", "-baselineVersion=0", "-validateMigrationNaming=true", "migrate"] 
    volumes:
      - ./db/migrations/voting-db:/flyway/sql
    depends_on:
      voting-db:
        condition: service_healthy
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${VOTING_DB_NAME}
      DATABASE_URL: ${VOTING_DATABASE_URL}
    env_file: .env
  
  backend-django:
    build:
      context: ./backend-django
    depends_on:
      main-db:
        condition: service_healthy
      map-db:
        condition: service_healthy
      map-flyway:
        condition: service_completed_successfully
      main-flyway:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend 
      - frontend
    volumes:
      - ./backend-django:/app
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    

  posting:
    networks:
      - backend
    build:
      context: ./posting
    ports:
      - "8085:8085"
    depends_on:
      map-db:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
    env_file:
      - .env

  email-service:
    networks:
      - backend
    build:
      context: ./mail-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8090:8080"

  password-service:
    networks:
      - backend
    build:
      context: ./daily-password
      dockerfile: Dockerfile
    depends_on:
      main-flyway:
        condition: service_completed_successfully
      email-service:
        condition: service_started
    env_file:
      - .env

  inquisitor-service:
    networks:
      - backend
    build:
      context: ./daily-inquisitor
      dockerfile: Dockerfile
    depends_on:
      main-flyway:
        condition: service_completed_successfully
      email-service:
        condition: service_started
    env_file:
      - .env
  
  voting-service:
    networks:
      - backend
      - frontend
    build:
      context: ./voting-service
      dockerfile: Dockerfile
    depends_on:
      main-flyway:
        condition: service_completed_successfully
      voting-flyway:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "4242:4242"
    

networks:
  backend:
    driver: bridge
    name: backend_net
  frontend:
    driver: bridge
    name: frontend_net

volumes:
  main_data_sql:
  uploads_data:
  map_data_sql:
  voting_data_sql:
