import os

MAIN_DATABASE_URL=os.getenv("USERS_DB_URL")
VOTING_DATABASE_URL=os.getenv("VOTING_DB_URL")
MAIL_SERVICE_URL=os.getenv("MAIL_URL")
PROMOTION_URL=os.getenv("PROMOTION_URL")
FRONTEND_SERVICE_URL=os.getenv("FRONTEND_SERVICE_URL")