import os

MAIN_DATABASE_URL=os.getenv("FLASK_MAIN_DATABASE_URL")
VOTING_DATABASE_URL=os.getenv("FLASK_VOTING_DATABASE_URL")
MAIL_SERVICE_URL=os.getenv("MAIL_URL")
PROMOTION_URL=os.getenv("PROMOTION_URL")
FRONTEND_SERVICE_URL=os.getenv("FRONTEND_SERVICE_URL")
