apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-all
  namespace: application
spec:
  provider: aws

  parameters:
    usePodIdentity: "true"
    region: "eu-north-1"

    objects: |
      - objectName: "SENDER"
        objectType: "secretsmanager"
        jmesPath:
          - path: "SENDER"
            objectAlias: "SENDER"

      - objectName: "PASSWORD"
        objectType: "secretsmanager"
        jmesPath:
          - path: "PASSWORD"
            objectAlias: "PASSWORD"

      - objectName: "SMTPHOST"
        objectType: "secretsmanager"
        jmesPath:
          - path: "SMTPHOST"
            objectAlias: "SMTPHOST"

      - objectName: "SMTPPORT"
        objectType: "secretsmanager"
        jmesPath:
          - path: "SMTPPORT"
            objectAlias: "SMTPPORT"

      - objectName: "MAIL_SERVICE_URL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MAIL_SERVICE_URL"
            objectAlias: "MAIL_SERVICE_URL"

      - objectName: "SECRET_KEY"
        objectType: "secretsmanager"
        jmesPath:
          - path: "SECRET_KEY"
            objectAlias: "SECRET_KEY"

      - objectName: "AUTH_URL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "AUTH_URL"
            objectAlias: "AUTH_URL"

      - objectName: "FRONTEND_SERVICE_URL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "FRONTEND_SERVICE_URL"
            objectAlias: "FRONTEND_SERVICE_URL"

      - objectName: "VITE_POSTING_SERVICE_URL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VITE_POSTING_SERVICE_URL"
            objectAlias: "VITE_POSTING_SERVICE_URL"

      - objectName: "VITE_AUTH_SERVICE_URL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VITE_AUTH_SERVICE_URL"
            objectAlias: "VITE_AUTH_SERVICE_URL"

      - objectName: "VITE_BACKEND_DJANGO_URL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VITE_BACKEND_DJANGO_URL"
            objectAlias: "VITE_BACKEND_DJANGO_URL"

      - objectName: "VITE_VOTING_API_BASE"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VITE_VOTING_API_BASE"
            objectAlias: "VITE_VOTING_API_BASE"

      - objectName: "USERS_DB_HOST"
        objectType: "secretsmanager"
        jmesPath:
          - path: "USERS_DB_HOST"
            objectAlias: "USERS_DB_HOST"

      - objectName: "USERS_DB_PORT"
        objectType: "secretsmanager"
        jmesPath:
          - path: "USERS_DB_PORT"
            objectAlias: "USERS_DB_PORT"

      - objectName: "USERS_DB_USER"
        objectType: "secretsmanager"
        jmesPath:
          - path: "USERS_DB_USER"
            objectAlias: "USERS_DB_USER"

      - objectName: "USERS_DB_PASSWORD"
        objectType: "secretsmanager"
        jmesPath:
          - path: "USERS_DB_PASSWORD"
            objectAlias: "USERS_DB_PASSWORD"

      - objectName: "USERS_DB_NAME"
        objectType: "secretsmanager"
        jmesPath:
          - path: "USERS_DB_NAME"
            objectAlias: "USERS_DB_NAME"

      - objectName: "MAP_DB_HOST"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MAP_DB_HOST"
            objectAlias: "MAP_DB_HOST"

      - objectName: "MAP_DB_PORT"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MAP_DB_PORT"
            objectAlias: "MAP_DB_PORT"

      - objectName: "MAP_DB_USER"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MAP_DB_USER"
            objectAlias: "MAP_DB_USER"

      - objectName: "MAP_DB_PASSWORD"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MAP_DB_PASSWORD"
            objectAlias: "MAP_DB_PASSWORD"
    
      - objectName: "MAP_DB_NAME"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MAP_DB_NAME"
            objectAlias: "MAP_DB_NAME"

      - objectName: "S3_BUCKET_NAME"
        objectType: "secretsmanager"
        jmesPath:
          - path: "S3_BUCKET_NAME"
            objectAlias: "S3_BUCKET_NAME"

      - objectName: "AWS_REGION"
        objectType: "secretsmanager"
        jmesPath:
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"

      - objectName: "VOTING_DB_HOST"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VOTING_DB_HOST"
            objectAlias: "VOTING_DB_HOST"

      - objectName: "VOTING_DB_PORT"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VOTING_DB_PORT"
            objectAlias: "VOTING_DB_PORT"

      - objectName: "VOTING_DB_USER"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VOTING_DB_USER"
            objectAlias: "VOTING_DB_USER"

      - objectName: "VOTING_DB_PASSWORD"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VOTING_DB_PASSWORD"
            objectAlias: "VOTING_DB_PASSWORD"

      - objectName: "VOTING_DB_NAME"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VOTING_DB_NAME"
            objectAlias: "VOTING_DB_NAME"

      - objectName: "AWS_ACCESS_KEY_ID"
        objectType: "secretsmanager"
        jmesPath:
          - path: "AWS_ACCESS_KEY_ID"
            objectAlias: "AWS_ACCESS_KEY_ID"

      
      - objectName: "AWS_SECRET_ACCESS_KEY"
        objectType: "secretsmanager"
        jmesPath:
          - path: "AWS_SECRET_ACCESS_KEY"
            objectAlias: "AWS_SECRET_ACCESS_KEY"

      - objectName: "VOTING_DB_URL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "VOTING_DB_URL"
            objectAlias: "VOTING_DB_URL"

      - objectName: "USERS_DB_URL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "USERS_DB_URL"
            objectAlias: "USERS_DB_URL"

      - objectName: "PROMOTION_URL"
        objectType: "secretsmanager"
        jmesPath:
          - path: "PROMOTION_URL"
            objectAlias: "PROMOTION_URL"

  secretObjects:
    - secretName: app-aws-secrets-map
      type: Opaque

      data:
        - objectName: SENDER
          key: SENDER

        - objectName: PASSWORD
          key: PASSWORD

        - objectName: SMTPHOST
          key: SMTPHOST

        - objectName: SMTPPORT
          key: SMTPPORT

        - objectName: MAIL_SERVICE_URL
          key: MAIL_SERVICE_URL

        - objectName: SECRET_KEY
          key: SECRET_KEY

        - objectName: AUTH_URL
          key: AUTH_URL

        - objectName: FRONTEND_SERVICE_URL
          key: FRONTEND_SERVICE_URL

        - objectName: VITE_POSTING_SERVICE_URL
          key: VITE_POSTING_SERVICE_URL

        - objectName: VITE_AUTH_SERVICE_URL
          key: VITE_AUTH_SERVICE_URL

        - objectName: VITE_BACKEND_DJANGO_URL
          key: VITE_BACKEND_DJANGO_URL

        - objectName: VITE_VOTING_API_BASE
          key: VITE_VOTING_API_BASE

        - objectName: USERS_DB_HOST
          key: USERS_DB_HOST

        - objectName: USERS_DB_PORT
          key: USERS_DB_PORT

        - objectName: USERS_DB_USER
          key: USERS_DB_USER

        - objectName: USERS_DB_PASSWORD
          key: USERS_DB_PASSWORD

        - objectName: USERS_DB_NAME
          key: USERS_DB_NAME

        - objectName: MAP_DB_HOST
          key: MAP_DB_HOST

        - objectName: MAP_DB_PORT
          key: MAP_DB_PORT

        - objectName: MAP_DB_USER
          key: MAP_DB_USER

        - objectName: MAP_DB_PASSWORD
          key: MAP_DB_PASSWORD

        - objectName: MAP_DB_NAME
          key: MAP_DB_NAME

        - objectName: S3_BUCKET_NAME
          key: S3_BUCKET_NAME

        - objectName: AWS_REGION
          key: AWS_REGION

        - objectName: AWS_ACCESS_KEY_ID
          key: AWS_ACCESS_KEY_ID

        - objectName: AWS_SECRET_ACCESS_KEY
          key: AWS_SECRET_ACCESS_KEY

        - objectName: VOTING_DB_HOST
          key: VOTING_DB_HOST

        - objectName: VOTING_DB_PORT
          key: VOTING_DB_PORT

        - objectName: VOTING_DB_USER
          key: VOTING_DB_USER

        - objectName: VOTING_DB_PASSWORD
          key: VOTING_DB_PASSWORD

        - objectName: VOTING_DB_NAME
          key: VOTING_DB_NAME

        - objectName: PROMOTION_URL
          key: PROMOTION_URL

        - objectName: USERS_DB_URL
          key: USERS_DB_URL

        - objectName: VOTING_DB_URL
          key: VOTING_DB_URL