apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: application
  labels:
    app: masonicapp
    microservice: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: frontend
  template:
    metadata:
      name: masonic-frontend
      labels:
        app: masonicapp
        microservice: frontend
    spec:
      serviceAccountName: app-service-account
      containers:
      - name: frontend-container
        image: 984546305184.dkr.ecr.eu-north-1.amazonaws.com/stage/masonic-frontend:latest
        env:
          - name: VITE_POSTING_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: app-aws-secrets-map
                key: VITE_POSTING_SERVICE_URL
          - name: VITE_AUTH_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: app-aws-secrets-map
                key: VITE_AUTH_SERVICE_URL
          - name: VITE_BACKEND_DJANGO_URL
            valueFrom:
              secretKeyRef:
                name: app-aws-secrets-map
                key: VITE_BACKEND_DJANGO_URL
          - name: VITE_VOTING_API_BASE
            valueFrom:
              secretKeyRef:
                name: app-aws-secrets-map
                key: VITE_VOTING_API_BASE
        volumeMounts:
        - name: secrets-volume
          mountPath: "/mnt/secrets"
          readOnly: true
      volumes:
      - name: secrets-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-secrets-all"