apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquisitor-deployment
  namespace: application
  labels:
    app: masonicapp
    microservice: inquisitor
spec:
  replicas: 1
  selector:
    matchLabels:
      microservice: inquisitor
  template:
    metadata:
      name: masonic-inquisitor
      labels:
        app: masonicapp
        microservice: inquisitor
    spec:
      serviceAccountName: app-service-account
      containers:
      - name: inquisitor-container
        image: 984546305184.dkr.ecr.eu-north-1.amazonaws.com/stage/masonic-inquisitor:latest
        env:
          - name: USERS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: app-aws-secrets-map
                key: USERS_DB_HOST
          - name: USERS_DB_PORT
            valueFrom:
              secretKeyRef:
                name: app-aws-secrets-map
                key: USERS_DB_PORT
          - name: USERS_DB_USER
            valueFrom:
              secretKeyRef:
                name: app-aws-secrets-map
                key: USERS_DB_USER
          - name: USERS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-aws-secrets-map
                key: USERS_DB_PASSWORD
          - name: USERS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: app-aws-secrets-map
                key: USERS_DB_NAME
          - name: MAIL_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: app-aws-secrets-map
                key: MAIL_SERVICE_URL
        volumeMounts:
        - name: secrets-volume
          mountPath: "/mnt/secrets"
          readOnly: true
      volumes:
      - name: secrets-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-secrets-all"