apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-es
  namespace: masonic-app
spec:
  refreshInterval: "1h"
  secretStoreRef: 
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: dev/paranormal/db-password
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: dev/paranormal/db-password
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: dev/paranormal/db-password
        property: host