name: Build and Push Docker image to ECR

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::914337380547:role/GitHubActionsRoleECR
      - name: Test list repositories
        run: |
          aws sts get-caller-identity
          aws ecr describe-repositories --output table
          